<?php

namespace Enroporra\EnroporraBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GoleadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoleadorRepository extends EntityRepository
{
}